{{- if .Values.monitor.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clowder.fullname" . }}-monitor
  labels:
{{ include "clowder.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "clowder.name" . }}-monitor
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "clowder.name" . }}-monitor
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      initContainers:
        - name: check-rabbitmq
          image: "{{ $.Values.image.checks }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: rabbitmq-uri
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}/monitor:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: monitor
              containerPort: 9999
              protocol: TCP
          env:
            - name: RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: rabbitmq-uri
            - name: CLOWDER_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: clowder-secret
          livenessProbe:
            tcpSocket:
              port: monitor
          readinessProbe:
            httpGet:
              path: {{ .Values.monitor.ingress.path }}
              port: monitor
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}