apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pecan.fullname" . }}-docs
  labels:
{{ include "pecan.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.docs.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pecan.name" . }}-docs
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "pecan.name" . }}-docs
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.project }}/docs:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: pecan-docs
              containerPort: 80
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: pecan-docs
          readinessProbe:
            httpGet:
              path: {{ .Values.ingress.path }}
              port: pecan-docs
          resources:
            {{- toYaml .Values.docs.resources | nindent 12 }}
      {{- with .Values.docs.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.docs.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.docs.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
