apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clowder.fullname" . }}
  labels:
{{ include "clowder.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "clowder.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "clowder.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: check-mongo
          image: "{{ $.Values.image.checks }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: mongodb-uri
{{- if not (or .Values.storage.s3 .Values.minio.enabled) }}
        - name: data-chown
          command: [chown, -R, "10001:root", /home/clowder/data]
          image: busybox:latest
          volumeMounts:
          - name: data
            mountPath: /home/clowder/data
{{- end }}
{{- if .Values.users }}
{{- $mongodburi := include "clowder.mongodburi" . }}
{{- range $index, $element := .Values.users }}
        - name: mongo-add-user-{{ $index }}
          image: "{{ $.Values.image.repository }}/mongo-init:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}
                  key: mongodb-uri
{{- if .username }}
            - name: USERNAME
              value: {{ .username | quote }}
{{- end }}
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}
                  key: "password-{{ $index }}"
            - name: EMAIL_ADDRESS
              value: {{ .email | quote }}
            - name: FIRST_NAME
              value: {{ .firstname | quote }}
            - name: LAST_NAME
              value: {{ .lastname | quote }}
            - name: ADMIN
              value: {{ .admin | quote }}
{{- end }}
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: clowder
              containerPort: 9000
              protocol: TCP
          env:
            - name: CLOWDER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: clowder-key
            - name: CLOWDER_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: clowder-secret
{{- if .Values.storage.s3 }}
            - name: S3_ACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: s3-access-key
            - name: S3_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: s3-secret-key
{{- else if .Values.minio.enabled }}
            - name: S3_ACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "clowder.fullname" . }}-minio
                  key: access-key
            - name: S3_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "clowder.fullname" . }}-minio
                  key: secret-key
{{- end }}
            - name: RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: rabbitmq-uri
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: mongodb-uri
          volumeMounts:
            - name: custom-volume
              mountPath: /home/clowder/custom
{{- if not (or .Values.storage.s3 .Values.minio.enabled) }}
            - name: data
              mountPath: /home/clowder/data
{{- end }}
          livenessProbe:
            tcpSocket:
              port: clowder
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: {{ .Values.ingress.path }}healthz
              port: clowder
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: custom-volume
          configMap:
            name: {{ include "clowder.fullname" . }}-config
            items:
              - key: custom.conf
                path: custom.conf
              - key: play.plugins
                path: play.plugins
{{- if not (or .Values.storage.s3 .Values.minio.enabled) }}
        - name: data
          persistentVolumeClaim:
{{- if $.Values.persistence.existingClaim }}
            claimName: {{ $.Values.persistence.existingClaim }}
{{- else }}
            claimName: {{ include "clowder.fullname" . }}-data
{{- end }}
{{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
