name: Update FAH Version

on:
  push:
    paths:
      - "charts/fah/**"
  schedule:
    # Run every Sunday at 2 AM UTC
    - cron: "0 2 * * 0"
  workflow_dispatch:

jobs:
  update:
    uses: ./.github/workflows/update-chart-version.yml
    with:
      chart_folder: fah
      chart_name: Folding@Home
      docker_tags_url: https://hub.docker.com/v2/repositories/linuxserver/foldingathome/tags?page_size=100
      docker_image: linuxserver/foldingathome
      chart_label: fah
      assignee: robkooper
